### ISSUE TITLE
IntoIterator not working

### ISSUE THREAD

**Issue by tjpalmer** [whatisaphone/genawaiter#22]
Probably just missing some Rust chops here, but the following doesn't work for me:

```rust
use genawaiter::rc::Gen;

fn count() -> Gen<i32, (), impl std::future::Future> {
    use genawaiter::rc::Co;
    async fn gen(co: Co<i32>) {
        let mut n = 1;
        while n < 10 {
            co.yield_(n).await;
            n += 2;
        }
    }
    Gen::new(gen)
}

fn main() {
    for i in count() {
        println!("{}", i);
    }
}
```

I get the following error:

```
error[E0277]: the trait bound `genawaiter::rc::generator::Gen<i32, (), impl std::future::Future>: std::iter::IntoIterator` is not satisfied
  --> src/main.rs:21:14
   |
21 |     for i in count() {
   |              ^^^^^^^ the trait `std::iter::IntoIterator` is not implemented for `genawaiter::rc::generator::Gen<i32, (), impl std::future::Future>`
   |
   = help: the following implementations were found:
             <genawaiter::rc::generator::Gen<Y, (), F> as std::iter::IntoIterator>
   = note: required by `std::iter::IntoIterator::into_iter`
```

But [my understanding from the docs is that this should work](https://github.com/whatisaphone/genawaiter/blob/c1696e9a97fd466fe82139608fdc6a3d570d2680/src/rc/mod.rs#L55).

My cargo dependency looks like this:

```toml
genawaiter = { version = "0.99.1", features = ["proc_macro"] }
```

**Comment by tjpalmer** [comment]
I'm still not sure what's wrong the above example, but I got a slightly different style working based on the linked list example in this repo, so I'll close this.

**Comment by whatisaphone** [comment]
I'm a bit late here, but I bet it would work if you tweaked the signature like this:

```diff
-fn count() -> Gen<i32, (), impl std::future::Future> {
+fn count() -> Gen<i32, (), impl std::future::Future<Output = ()>> {
```

The `IntoIterator` implementation restricts `Output` to `()` because, if it didn't, there would be nowhere for the output value to go and data would be lost.
