### ISSUE TITLE
Guidance for recursive generators

### ISSUE THREAD

**Issue by alercah** [whatisaphone/genawaiter#24]
I tried and failed to write a recursive generator today. I understand that this relates to the inherent problem of recursive async functions in Rust, but it's not clear how to write a recursive generator; documentation on that would be appreciated especially if it ends up being useful in the future when generators make it to the stdlib.

**Comment by whatisaphone** [comment]
That's a great idea for an example. [Added!](https://github.com/whatisaphone/genawaiter/blob/45c10c223b92da215e182bc3eff0d5e09bf813f4/examples/recursion.rs)

**Comment by alercah** [comment]
Thanks!

**Comment by alercah** [comment]
Ah, I think part of the issue was that only `sync` supports `new_boxed`, not `rc`. Is there a reason for that?
