### ISSUE TITLE
Easy error propagation?

### ISSUE THREAD

**Issue by vorot93** [whatisaphone/genawaiter#6]
Currently if I want to propagate errors I have to do:
```
move |co| {
  async move {
    if let Err(e) = async {
      co.yield_(my_fallible_op()?).await;
      Ok(())
    }.await {
      co.yield_(Err(e)).await;
    }
  }
}
```

This is not very ergonomic.

**Comment by whatisaphone** [comment]
I wonder if you're hitting a limitation of type inference with closures. The question mark works for me if I use a plain `fn`:

```rust
use genawaiter::sync::{Co, Gen};

struct MyError;

fn run() {
    Gen::new(produce);
}

async fn produce(co: Co<i32>) -> Result<(), MyError> {
    let result: i32 = my_fallible_op()?;
    co.yield_(result).await;
    Ok(())
}

fn my_fallible_op() -> Result<i32, MyError> {
    Ok(10)
}
```

**Comment by vorot93** [comment]
If I'm reading this correctly, `Stream` is [only implemented](https://github.com/whatisaphone/genawaiter/blob/master/src/sync/stream.rs#L8) for the driving `Future`s that return `()` which would preclude any kind of error propagation.

**Comment by whatisaphone** [comment]
I added an example showing how to propagate errors: https://github.com/whatisaphone/genawaiter/blob/8d9416b4bc9d7906ed5280d090d970bb15cc45ba/examples/error_propagation/src/main.rs

The pattern is pretty similar to the [fallible_iterator](https://docs.rs/fallible-iterator/0.2.1/fallible_iterator/) crate, so you can also look there for inspiration.

Feel free to reopen if you have more questions
